/**
 * Planning-card export (plan §25 Phase 4 "preview export"): one PNG a photographer can drop in a
 * shot list or send to a client. Two halves:
 *
 *   buildPlanningCard(scene)      → pure data model (strings), unit tested;
 *   renderPlanningCardPng(model)  → draws the model on a canvas in the browser.
 *
 * The card always carries the source label, the confidence breakdown, the weather mode
 * (forecast vs scenario) and provider attribution — the honesty rules in RENDERING_ACCURACY.md
 * apply to exports exactly as they do on screen. Nothing on the card is generated by AI.
 */
import { formatWallTime } from '@lightmap/astronomy';
import { brand } from '@lightmap/config';
import { compassLabel } from '@lightmap/geospatial';
import { lightingFromScene } from '@lightmap/renderer';
import { SOURCE_MODE_LABEL, type SceneState, type SourceMode } from '@lightmap/scene';
import { scenarioById } from '@lightmap/weather';

export interface PlanningCardModel {
  title: string;
  subtitle: string;
  dateLine: string;
  sourceMode: SourceMode;
  sourceLabel: string;
  weatherLine: string;
  facts: Array<{ label: string; value: string }>;
  confidence: Array<{ label: string; level: string }>;
  notes: string[];
  attribution: string[];
  skyGradient: [string, string, string];
  fileName: string;
}

const WEEKDAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

function humanDate(iso: string): string {
  const [y, m, d] = iso.split('-').map(Number);
  if (!y || !m || !d) return iso;
  const dow = new Date(Date.UTC(y, m - 1, d)).getUTCDay();
  return `${WEEKDAYS[dow]} ${d} ${MONTHS[m - 1]} ${y}`;
}

function slug(s: string): string {
  return (
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 40) || 'place'
  );
}

export function buildPlanningCard(
  scene: SceneState,
  opts: { generatedAt: Date; appUrl?: string } = { generatedAt: new Date() },
): PlanningCardModel {
  const tz = scene.location.timeZone;
  const s = scene.solar;
  const ev = scene.dayEvents;
  const a = scene.atmosphere;
  const t = (d: Date | null) => (d ? formatWallTime(d, tz) : '—');
  const scenario = scenarioById(a.scenario).label;
  const isForecast = a.mode === 'FORECAST' || a.mode === 'EXTENDED_FORECAST';
  const isPast = a.mode === 'RECENT_PAST' || a.mode === 'PAST';

  const weatherLine = isForecast
    ? `Forecast${a.providerId ? ` (${a.providerId})` : ''}: ${scenario} · ${Math.round(a.parameters.sunTransmittance * 100)} % direct light · confidence ${scene.confidence.weather}${a.mode === 'EXTENDED_FORECAST' ? ' · extended range, lower certainty' : ''}`
    : isPast
      ? `Observed conditions: ${scenario} · ${Math.round(a.parameters.sunTransmittance * 100)} % direct light`
      : `Scenario (not a forecast): ${scenario} · ${Math.round(a.parameters.sunTransmittance * 100)} % direct light`;

  const facts: Array<{ label: string; value: string }> = [
    {
      label: 'Sun',
      value:
        s.elevationDegrees > -0.833
          ? `${s.elevationDegrees.toFixed(1)}° up · ${Math.round(s.azimuthDegrees)}° ${compassLabel(s.azimuthDegrees)}`
          : `${Math.abs(s.elevationDegrees).toFixed(1)}° below horizon · ${Math.round(s.azimuthDegrees)}° ${compassLabel(s.azimuthDegrees)}`,
    },
    {
      label: 'Light',
      value: `${s.phase.replace('-', ' ')} · ${Math.round(a.colorTemperatureK)} K`,
    },
    { label: 'Sunrise / sunset', value: `${t(ev.sunrise)} / ${t(ev.sunset)}` },
    {
      label: 'Golden hour',
      value: `${t(ev.goldenHourMorningStart)}–${t(ev.goldenHourMorningEnd)} · ${t(ev.goldenHourEveningStart)}–${t(ev.goldenHourEveningEnd)}`,
    },
    {
      label: 'Blue hour',
      value: `${t(ev.dawn)}–${t(ev.sunrise)} · ${t(ev.sunset)}–${t(ev.civilDusk)}`,
    },
    { label: 'Solar noon', value: `${t(ev.solarNoon)} · max ${ev.maxElevationDeg.toFixed(1)}°` },
  ];
  if (scene.lunar)
    facts.push({
      label: 'Moon',
      value: `${scene.lunar.phaseName} · ${Math.round(scene.lunar.illuminatedFraction * 100)} % · ${
        scene.lunar.isAboveHorizon
          ? `${scene.lunar.elevationDegrees.toFixed(0)}° up ${compassLabel(scene.lunar.azimuthDegrees)}`
          : 'below horizon'
      }`,
    });
  const c = scene.camera;
  facts.push({
    label: 'Camera',
    value: `${c.mode === 'viewpoint' ? 'Viewpoint' : 'Map'} · ${Math.round(c.headingDeg)}° ${compassLabel(c.headingDeg)} · pitch ${c.pitchDeg.toFixed(0)}° · ${c.focalLengthMm ? `${c.focalLengthMm} mm` : `${c.fovDeg.toFixed(0)}° FOV`}`,
  });
  if (ev.polar !== 'normal') facts.push({ label: 'Note', value: ev.polar.replace('-', ' ') });
  const th = scene.terrainHorizon;
  if (th?.sunEvents.differsFromAstronomical)
    facts.push({
      label: 'Over the terrain',
      value: `first light ${t(th.sunEvents.firstLight)} · last light ${t(th.sunEvents.lastLight)} (terrain only; trees and buildings not modelled)`,
    });
  if (th && scene.solar.isAboveHorizon && !th.sunAboveTerrain)
    facts.push({
      label: 'Right now',
      value: `sun behind the terrain (ridge ${th.horizonAtSunDeg.toFixed(1)}°, sun ${scene.solar.elevationDegrees.toFixed(1)}°)`,
    });

  const confidence = [
    { label: 'Astronomy', level: scene.confidence.astronomy },
    { label: 'Terrain', level: scene.confidence.terrain },
    { label: 'Scene detail', level: scene.confidence.sceneDetail },
    { label: 'Weather', level: scene.confidence.weather },
    { label: 'Real reference', level: scene.confidence.imagery === 'NONE' ? 'None' : 'Yes' },
  ];

  const notes: string[] = [];
  notes.push(
    scene.sourceMode === 'REAL_REFERENCE'
      ? 'Real reference: a licensed photograph of the place, not this date or time.'
      : scene.sourceMode === 'SIMULATED_LIGHTING'
        ? 'Simulated lighting: real terrain and map geometry; light and atmosphere computed for this instant.'
        : 'Estimated preview: imagery or geometry is incomplete here; light direction is exact, the scene is approximate.',
  );
  if (!isForecast && !isPast)
    notes.push('Weather shown is a chosen scenario. No forecast exists this far ahead.');
  if (scene.environment.fixtureMode)
    notes.push('Development fixture data was active when this card was made.');

  const attribution = [
    ...scene.environment.attributions.map((x) => x.attribution),
    ...(a.providerAttribution ? [a.providerAttribution] : []),
    `Made with ${brand.name} · ${opts.appUrl ?? brand.urls.marketing} · ${opts.generatedAt.toISOString().slice(0, 16).replace('T', ' ')} UTC`,
  ];

  const light = lightingFromScene(scene);
  const dateLine = `${humanDate(scene.localTime.date)} · ${scene.localTime.time} ${scene.localTime.zoneAbbreviation}`;

  return {
    title: scene.location.label,
    subtitle: `${scene.location.point.latitude.toFixed(4)}, ${scene.location.point.longitude.toFixed(4)} · ${tz}${
      scene.environment.groundElevationM !== null
        ? ` · ${Math.round(scene.environment.groundElevationM)} m`
        : ''
    }`,
    dateLine,
    sourceMode: scene.sourceMode,
    sourceLabel: SOURCE_MODE_LABEL[scene.sourceMode].toUpperCase(),
    weatherLine,
    facts,
    confidence,
    notes,
    attribution,
    skyGradient: light.skyGradient,
    fileName: `${brand.slug}-${slug(scene.location.label)}-${scene.localTime.date}-${scene.localTime.time.replace(':', '')}.png`,
  };
}

/* ------------------------------------------------------------------------------------------ */
/* Canvas rendering (browser only)                                                             */
/* ------------------------------------------------------------------------------------------ */

const W = 1200;
const PAD = 56;
const SOURCE_COLORS: Record<SourceMode, string> = {
  REAL_REFERENCE: '#4ade80',
  SIMULATED_LIGHTING: '#f5b342',
  ESTIMATED_PREVIEW: '#94a3b8',
};

function wrap(ctx: CanvasRenderingContext2D, text: string, maxWidth: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let cur = '';
  for (const w of words) {
    const test = cur ? `${cur} ${w}` : w;
    if (ctx.measureText(test).width > maxWidth && cur) {
      lines.push(cur);
      cur = w;
    } else cur = test;
  }
  if (cur) lines.push(cur);
  return lines;
}

function ellipsize(ctx: CanvasRenderingContext2D, text: string, maxWidth: number): string {
  if (ctx.measureText(text).width <= maxWidth) return text;
  let t = text;
  while (t.length > 1 && ctx.measureText(`${t}…`).width > maxWidth) t = t.slice(0, -1);
  return `${t.trimEnd()}…`;
}

async function loadImage(dataUrl: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error('image failed to load'));
    img.src = dataUrl;
  });
}

/**
 * Render the card to a PNG blob. `imageDataUrl` is the renderer capture (may be null when the
 * 3D preview is unavailable: the card then shows the sky gradient band instead of a picture).
 */
export async function renderPlanningCardPng(
  model: PlanningCardModel,
  imageDataUrl: string | null,
): Promise<Blob> {
  const image = imageDataUrl ? await loadImage(imageDataUrl).catch(() => null) : null;
  const imageH = image ? Math.round((W * 9) / 16) : 220;
  const font = (px: number, weight = 400) =>
    `${weight} ${px}px system-ui, -apple-system, "Segoe UI", Roboto, sans-serif`;

  // Measure first: the height depends on wrapped text.
  const measure = document.createElement('canvas');
  const mctx = measure.getContext('2d');
  if (!mctx) throw new Error('canvas unavailable');
  const colW = (W - PAD * 2 - 32) / 2;
  mctx.font = font(26);
  const factLines = model.facts.map((f) => wrap(mctx, f.value, colW - 8));
  const rows = Math.ceil(model.facts.length / 2);
  let factsH = 0;
  for (let r = 0; r < rows; r++) {
    const l = Math.max(factLines[r * 2]?.length ?? 1, factLines[r * 2 + 1]?.length ?? 1);
    factsH += 34 + l * 32 + 18;
  }
  mctx.font = font(22);
  const noteLines = model.notes.flatMap((n) => wrap(mctx, n, W - PAD * 2));
  mctx.font = font(18);
  const attrLines = model.attribution.flatMap((a) => wrap(mctx, a, W - PAD * 2));
  mctx.font = font(24);
  const weatherLines = wrap(mctx, model.weatherLine, W - PAD * 2);
  // Confidence chips wrap when the five labels exceed the width; measure the rows the same way
  // the draw loop lays them out so the height budget is exact.
  mctx.font = font(18, 600);
  let chipRows = 1;
  {
    let x = PAD;
    for (const c of model.confidence) {
      const w = mctx.measureText(`${c.label}: ${c.level}`).width + 28;
      if (x + w > W - PAD) {
        chipRows++;
        x = PAD;
      }
      x += w + 12;
    }
  }
  mctx.font = font(44, 700);
  const title = ellipsize(mctx, model.title, W - PAD * 2);

  const H =
    imageH +
    PAD +
    56 + // title
    36 + // subtitle
    52 + // date line
    weatherLines.length * 32 +
    24 +
    factsH +
    24 +
    36 +
    (chipRows - 1) * 44 +
    34 + // confidence chips
    noteLines.length * 30 +
    24 +
    attrLines.length * 26 +
    PAD;

  const canvas = document.createElement('canvas');
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext('2d');
  if (!ctx) throw new Error('canvas unavailable');

  // Background
  ctx.fillStyle = brand.colors.chrome;
  ctx.fillRect(0, 0, W, H);

  // Picture or sky band
  if (image) {
    const scale = Math.max(W / image.width, imageH / image.height);
    const dw = image.width * scale;
    const dh = image.height * scale;
    ctx.drawImage(image, (W - dw) / 2, (imageH - dh) / 2, dw, dh);
  } else {
    const g = ctx.createLinearGradient(0, 0, 0, imageH);
    g.addColorStop(0, model.skyGradient[0]);
    g.addColorStop(0.6, model.skyGradient[1]);
    g.addColorStop(1, model.skyGradient[2]);
    ctx.fillStyle = g;
    ctx.fillRect(0, 0, W, imageH);
    ctx.fillStyle = 'rgba(255,255,255,0.85)';
    ctx.font = font(22);
    ctx.fillText('Sky gradient for this moment (3D preview not captured)', PAD, imageH - 24);
  }
  // Source badge on the picture (text + colour, never colour alone)
  ctx.font = font(22, 700);
  const badgeW = ctx.measureText(model.sourceLabel).width + 40;
  ctx.fillStyle = 'rgba(0,0,0,0.65)';
  ctx.fillRect(PAD, 28, badgeW, 44);
  ctx.fillStyle = SOURCE_COLORS[model.sourceMode];
  ctx.fillRect(PAD, 28, 6, 44);
  ctx.fillStyle = '#ffffff';
  ctx.fillText(model.sourceLabel, PAD + 22, 58);

  let y = imageH + PAD;
  ctx.fillStyle = brand.colors.text;
  ctx.font = font(44, 700);
  ctx.fillText(title, PAD, y);
  y += 56;
  ctx.fillStyle = brand.colors.textMuted;
  ctx.font = font(22);
  ctx.fillText(model.subtitle, PAD, y);
  y += 36;
  ctx.fillStyle = brand.colors.sun;
  ctx.font = font(30, 600);
  ctx.fillText(model.dateLine, PAD, y + 8);
  y += 52;
  ctx.fillStyle = brand.colors.text;
  ctx.font = font(24);
  for (const line of weatherLines) {
    ctx.fillText(line, PAD, y);
    y += 32;
  }
  y += 24;

  // Facts grid
  for (let r = 0; r < rows; r++) {
    const rowLines = Math.max(factLines[r * 2]?.length ?? 1, factLines[r * 2 + 1]?.length ?? 1);
    const rowH = 34 + rowLines * 32 + 18;
    for (let ci = 0; ci < 2; ci++) {
      const f = model.facts[r * 2 + ci];
      if (!f) continue;
      const x = PAD + ci * (colW + 32);
      ctx.fillStyle = 'rgba(255,255,255,0.05)';
      ctx.fillRect(x, y, colW, rowH - 10);
      ctx.fillStyle = brand.colors.textMuted;
      ctx.font = font(16, 600);
      ctx.fillText(f.label.toUpperCase(), x + 16, y + 26);
      ctx.fillStyle = brand.colors.text;
      ctx.font = font(26);
      let ly = y + 60;
      for (const l of factLines[r * 2 + ci] ?? []) {
        ctx.fillText(l, x + 16, ly);
        ly += 32;
      }
    }
    y += rowH;
  }
  y += 24;

  // Confidence chips
  ctx.font = font(18, 600);
  let cx = PAD;
  for (const c of model.confidence) {
    const label = `${c.label}: ${c.level}`;
    const w = ctx.measureText(label).width + 28;
    if (cx + w > W - PAD) {
      cx = PAD;
      y += 44;
    }
    ctx.fillStyle = 'rgba(255,255,255,0.08)';
    ctx.fillRect(cx, y, w, 36);
    ctx.fillStyle = brand.colors.text;
    ctx.fillText(label, cx + 14, y + 25);
    cx += w + 12;
  }
  y += 70;

  ctx.fillStyle = brand.colors.textMuted;
  ctx.font = font(22);
  for (const l of noteLines) {
    ctx.fillText(l, PAD, y);
    y += 30;
  }
  y += 24;
  ctx.fillStyle = 'rgba(255,255,255,0.45)';
  ctx.font = font(18);
  for (const l of attrLines) {
    ctx.fillText(l, PAD, y);
    y += 26;
  }

  return new Promise((resolve, reject) => {
    canvas.toBlob((b) => (b ? resolve(b) : reject(new Error('toBlob failed'))), 'image/png');
  });
}

/** Trigger a browser download of the blob. */
export function downloadBlob(blob: Blob, fileName: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
